# -*- mode: ruby -*-
# vi: set ft=ruby :

serverMaster="ciglesiaS"
IPMaster="192.168.56.110"

# Vagrant configuration version: 2
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider :virtualbox do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Server Master
  config.vm.define serverMaster do |server|
    server.vm.hostname = serverMaster
    server.vm.network "private_network", ip: IPMaster
    server.vm.provision "shell", path: "scripts/k3s_master.sh"
    server.vm.provision "shell", path: "scripts/new_manifest.sh"
    server.vm.network "forwarded_port", guest: 80, host: 8888
  end

end
