# -*- mode: ruby -*-
# vi: set ft=ruby :

serverMaster="jiglesiaS"
IPMaster="192.168.56.110"
appHostnames = ["app1.com", "app2.com", "app3.com"]

# Vagrant configuration version: 2
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider :virtualbox do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
  export DEBIAN_FRONTEND=noninteractive \
    && sudo apt-get update && sudo apt-get install -y curl
  SHELL
  # Synced Folder Configuration
  config.vm.synced_folder "~/.ssh", "/host_ssh"

  # Server Master
  config.vm.define serverMaster do |server|
    server.vm.hostname = serverMaster
    server.vm.network "private_network", ip: IPMaster
    server.vm.provision "shell", privileged: true, inline: <<-SHELL
      mkdir -p /root/.ssh
      cp /host_ssh/id_rsa.pub /root/.ssh/authorized_keys
    SHELL
    server.vm.provision "shell", path: "setup/k3s_master.sh", args: [IPMaster] + appHostnames
    server.vm.provision "shell", privileged: true, inline: <<-SHELL
      # Apply Kubernetes manifests for applications
      kubectl apply -f /vagrant/app1-deployment.yaml
      kubectl apply -f /vagrant/app2-deployment.yaml
      kubectl apply -f /vagrant/app3-deployment.yaml
      kubectl apply -f /vagrant/ingress.yaml
    SHELL
  end

end
