# -*- mode: ruby -*-
# vi: set ft=ruby :

serverMaster="ciglesiaS"
IPMaster="192.168.56.110"
serverWorker="ciglesiaSW"
IPWorker="192.168.56.111"

# Vagrant configuration version: 2
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider :virtualbox do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
  export DEBIAN_FRONTEND=noninteractive \
    && sudo apt-get update && sudo apt-get install -y curl
  SHELL
  # Synced Folder Configuration
  config.vm.synced_folder "~/.ssh", "/host_ssh"

  # Server Master
  config.vm.define serverMaster do |server|
    server.vm.hostname = serverMaster
    server.vm.network "private_network", ip: IPMaster
    server.vm.provision "shell", privileged: true, inline: <<-SHELL
      mkdir -p /root/.ssh
      cp /host_ssh/id_rsa.pub /root/.ssh/authorized_keys
    SHELL
    server.vm.provision "shell", path: "scripts/k3s_master.sh"
  end

  # Server Worker
  config.vm.define serverWorker do |server_worker|
    server_worker.vm.hostname = serverWorker
    server_worker.vm.network "private_network", ip: IPWorker
    server_worker.vm.provision "shell", privileged: true, inline: <<-SHELL
      mkdir -p /root/.ssh
      cp /host_ssh/id_rsa.pub /root/.ssh/authorized_keys
    SHELL
    server_worker.vm.provision "shell", path: "scripts/k3s_agent.sh"
  end

end
