# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration version: 2
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider :virtualbox do |vb|
    vb.memory = "4096"
    vb.cpus = 4
  end

  # Server Master
  config.vm.define "p3" do |server|
    server.vm.hostname = "p3"
    server.vm.provision "shell", path: "scripts/k3d.sh"
    server.vm.provision "shell", path: "scripts/argocd.sh"
  end

end
